// This file has been generated by Specta. DO NOT EDIT.

/**
 * 知识树块（含 parent_id，9 字段）
 */
export type KnowledgeTreeBlockDto = { id: string; title: string; category: string; content: string; tags: string | null; blockType: string | null; parentId: string | null; createdAt: string | null; updatedAt: string | null }

export type FileOcrStateDto = { fileId: string; ocrStatus: string; hasText: boolean }

export type CasePersonDto = { linkId: string; person: PersonDto; role: string | null }

/**
 * 比较飞书记录 vs 本地记录
 */
export type RecordDiff = { same: RecordDiffItem[]; feishuOnly: RecordDiffItem[]; localOnly: RecordDiffItem[]; conflict: RecordDiffItem[] }

/**
 * 分级预警结果
 */
export type DeadlineWarning = { deadlineId: string; caseId: string; caseName: string; deadlineName: string; dueDate: string; daysLeft: number; level: string; levelLabel: string; levelColor: string; message: string }

export type FeishuSyncReport = { pulled: number; pushed: number; created: number; updated: number; skipped: number; errors: string[]; syncedAt: string }

/**
 * 映射条目（B1 类型化：入参直用强类型，缺省口径与原 parse_mappings 一致）
 */
export type MappingEntry = { feishuFieldName: string; feishuFieldType: number; localColumn: string; syncDirection: string; isFormula: boolean; isLink: boolean }

/**
 * 案件导入配置
 */
export type CaseImportConfig = { headerRow: number; columnMappings: { [key: number]: string }; forwardFillColumns: number[]; conflictStrategy: string; defaultTrack: string | null }

export type PageIndexImportResultDto = { knowledgeId: string; childCount: number; reused: boolean }

/**
 * 领域条目
 */
export type AreaDto = { id: string; name: string; description: string | null; icon: string | null; sortOrder: number; createdAt: string; updatedAt: string }

export type UpcomingHearing = { id: string; title: string; date: string; caseId: string; caseName: string; daysLeft: number }

/**
 * 双版本对比结果
 */
export type KnowledgeDiffVersionsResult = { version1: VersionMetaDto; version2: VersionMetaDto; diffs: DiffLineDto[] }

/**
 * 保存自定义模板（创建或更新），禁止编辑内置模板
 * 文件夹模板输出（B1 类型化）
 */
export type FolderTemplateOutput = { id: string; name: string; caseType: string; isBuiltin: number; directories: any; fileNaming: any | null; createdAt: string | null }

/**
 * 草稿实体（docs 域）
 * 
 * 契约（审查 P1-1）：Tauri v2 **只对入参**做 camelCase→snake_case 自动转换，
 * 返回值序列化完全由 serde 决定。缺 rename_all 时下行 JSON 为 snake_case
 * （case_id / template_path / created_at / updated_at），而前端 `core/services/docs.ts`
 * 按 camelCase（caseId / templatePath / createdAt / updatedAt）断言与消费，导致
 * 草稿字段在编辑器里恒为 undefined。与 docs.rs 的 RenderResponse / ExportResponse 同源问题。
 */
export type Draft = { id: string; caseId: string | null; title: string; content: string | null; templatePath: string | null; status: string; version: number; createdAt: string; updatedAt: string }

export type ReminderLogEntry = { id: string; ruleId: string; caseId: string | null; taskId: string | null; channel: string; message: string; level: string | null; status: string; sentAt: string | null }

export type PersonCaseDto = { linkId: string; caseId: string; caseName: string; caseNo: string | null; role: string | null }

/**
 * 任务类型化更新契约（P1-2：三态字段 + 服务端校验 + 影响行数断言）
 */
export type UpdateTaskPatch = { id: string; origin?: string | null; proposalToken?: string | null; taskName?: PatchField<string>; description?: PatchField<string>; deadline?: PatchField<string>; priority?: PatchField<string>; completed?: PatchField<number>; assignee?: PatchField<string>; finishNote?: PatchField<string>; taskType?: PatchField<string>; startDate?: PatchField<string>; dueDate?: PatchField<string>; dueTime?: PatchField<string>; waitingFor?: PatchField<string>; followUpDate?: PatchField<string>; context?: PatchField<string>; flagged?: PatchField<number>; sequential?: PatchField<number>; blocked?: PatchField<number>; blockedReason?: PatchField<string>; sequenceOrder?: PatchField<number>; startBucket?: PatchField<string>; todayIndex?: PatchField<number>; estimatedMinutes?: PatchField<number>; actualMinutes?: PatchField<number>; areaId?: PatchField<string>; caseId?: PatchField<string>; timeBlock?: PatchField<string>; parentTaskId?: PatchField<string>; recurrenceRule?: PatchField<string>; isFocus?: PatchField<number>; deferUntil?: PatchField<string> }

/**
 * 字段级 Diff 行（before = 目标实体当前值，after = 提案将写入的值）
 */
export type ProposalFieldDiff = { field: string; before: any | null; after: any | null; changed: boolean }

export type WhiteboardDto = { id: string; caseId: string; name: string; nodeCount: number; createdAt: string | null; updatedAt: string | null }

/**
 * 列表查询结果
 */
export type CaseListResult = { items: Case[]; total: number; page: number; perPage: number }

export type FieldDiffItem = { feishuField: string | null; feishuType: string | null; feishuTypeCode: number | null; localColumn: string | null; localType: string | null; status: string }

/**
 * 导出结果响应
 * 
 * 契约（审查 P1-1）：同上。缺 rename_all 时前端 `result.data.outputPath`
 * 恒为 undefined，表现为「DOCX 已导出: undefined」且导出后「打开文件」必然失败
 * （`DocumentGenView.vue:499` / `:506`）。
 */
export type ExportResponse = { outputPath: string; fileSize: number; exportedAt: string }

export type SyncStatus = { webdavConnected: boolean; webdavUrl: string; lastSyncAt: string | null; deviceVersion: number; remoteEtag: string | null; pendingChanges: boolean }

/**
 * 仪表盘聚合数据
 */
export type DashboardStats = { activeCount: number; totalCount: number; closedCount: number; deadlineWarnings: DeadlineResult[]; recentActivities: RecentActivity[]; byTrack: ([string, number])[] }

export type ReminderRule = { id: string; name: string; triggerType: string; triggerValue: number | null; channels: string; messageTemplate: string | null; caseTypes: string | null; enabled: boolean; createdAt: string | null }

/**
 * 字段分组（B1 类型化）
 */
export type FieldGroup = { id: string; name: string; description: string | null; caseTypes: any | null; courtLevels: any | null; sortOrder: number; items: FieldGroupItem[] }

export type FeishuBitableInspectResult = { appToken: string; tableId: string; tableName: string; tables: FeishuTableMeta[]; totalRecords: number; columns: ColumnMappingRecommendation[]; previewRows: { [key: string]: any }[] }

/**
 * 即时判断结果
 */
export type QuickJudgeResult = { category: string; confidence: number; strength: string; recommendations: QuickRecommendation[]; aiAvailable: boolean; aiAnalyzed: boolean }

/**
 * 渲染结果响应
 * 
 * 契约（审查 P1-1）：Tauri v2 **只对入参**做 camelCase→snake_case 自动转换，
 * 返回值序列化完全由 serde 决定。缺 rename_all 时下行 JSON 为 snake_case，
 * 而前端 `core/services/docs.ts:46-59` 按 camelCase 断言，导致
 * `usedFields` / `missingFields` 恒为 undefined —— 「有 N 个字段未填充」
 * 告警永不显示（生成正式文书时唯一的占位符防线）。
 */
export type RenderResponse = { html: string; text: string; usedFields: { [key: string]: string }; missingFields: string[] }

/**
 * 列表查询过滤条件
 */
export type CaseFilter = { track: string | null; client: string | null; court: string | null; status: string | null; search: string | null; dateFrom: string | null; dateTo: string | null; sortBy: string | null; page: number | null; perPage: number | null; caseRoute: string | null; civilStatus: string | null; invalidationStatus: string | null; adminStatus: string | null }

/**
 * 统计（byCategory 保持原 [分类,计数] 元组数组形状）
 */
export type KnowledgeStatsDto = { total: number; byCategory: ([string, number])[] }

/**
 * 版本元信息
 */
export type VersionMetaDto = { id: string; changedAt: string | null; changeReason: string | null }

export type DocumentJobDto = { id: string; fileId: string; sourceSha256: string; status: string; engine: string; modelVersion: string | null; currentPage: number; totalPages: number; progress: number; searchablePdfPath: string | null; pageIrPath: string | null; markdownPath: string | null; errorCode: string | null; errorMessage: string | null; createdAt: string; updatedAt: string }

export type KnowledgeExportDto = { outputPath: string; fileSize: number; exportedAt: string }

export type PersonDto = { id: string; kind: string; name: string; org: string | null; phone: string | null; email: string | null; preferences: string | null; notes: string | null; createdAt: string | null; updatedAt: string | null; caseCount: number | null }

export type NameCount = { label: string; value: number }

export type KnowledgeDocumentSourceDto = { fileId: string; caseId: string; fileName: string; caseName: string; totalPages: number; markdownPath: string | null; searchablePdfPath: string | null; importedKnowledgeId: string | null }

/**
 * 新建结果（保持原 {id} 形状，消费方零改动）
 */
export type CreateAreaOutput = { id: string }

/**
 * 案件统一视图行（B1 类型化）
 */
export type CaseUnifiedView = { id: string; caseName: string | null; caseNo: string | null; clientName: string | null; causeAction: string | null; track: string | null; status: string | null; court: string | null; caseLevel: string | null; operator: string | null; trialDate: string | null; filingDate: string | null; nextDeadline: string | null; nextHearing: string | null; updatedAt: string | null }

export type SyncResult = { direction: string; success: boolean; message: string; conflict: boolean; localEtag: string | null; remoteEtag: string | null }

/**
 * 知识块（列表视图，8 字段）
 */
export type KnowledgeBlockDto = { id: string; title: string; category: string; content: string; tags: string | null; blockType: string | null; createdAt: string | null; updatedAt: string | null }

/**
 * 检索结果条目
 */
export type SearchResult = { id: string; title: string; category: string; content: string; tags: string | null; lawName: string | null; articleNo: string | null; score: number; source: string }

/**
 * 全局搜索结果项（轻量列）
 */
export type SearchTaskDto = { id: string; taskName: string; dueDate: string | null; completed: number; startBucket: string | null }

export type DocumentEngineStatus = { available: boolean; executable: string | null; version: string | null; rendererAvailable: boolean; coordinateModelAvailable: boolean; ovisModelAvailable: boolean; searchablePdfAvailable: boolean; missing: string[]; error: string | null }

/**
 * 今日面板统计（B1 类型化）
 */
export type TodayStats = { hardSchedule: number; dueToday: number; waitingOverdue: number; needReview: number }

/**
 * AI 处理结果（分类 + 置信度 + 抽取 + 自动路由动作）
 */
export type ProcessedInboxResult = { category: string; confidence: number; suggestedCaseId: string | null; caseNo: string | null; extracted: any | null; routeActions: any[] }

/**
 * 任务列表项（B1 类型化：返回侧 Value → 强类型；字段与前端手写 Task 契约一致）
 */
export type TaskDto = { id: string; caseId: string | null; taskName: string; description: string | null; createdDate: string; deadline: string | null; priority: string | null; completed: number; assignee: string | null; finishNote: string | null; taskType: string; startDate: string | null; dueDate: string | null; waitingFor: string | null; followUpDate: string | null; context: string | null; flagged: number; sequential: number; blocked: number; sequenceOrder: number; startBucket: string; todayIndex: number; estimatedMinutes: number | null; actualMinutes: number | null; isOverdue: number; dueSoon: number; lastReviewDate: string | null; nextReviewDate: string | null; areaId: string | null; knowledgeId: string | null; parentTaskId: string | null; recurrenceRule: string | null; isFocus: number; deferUntil: string | null }

export type GlobalSearchResult = { itemType: string; id: string; title: string; category: string; snippet: string | null }

export type CalendarEvent = { id: string; date: string; title: string; eventType: string; caseId: string; caseName: string; startTime?: string | null; endTime?: string | null; allDay?: boolean | null }

export type LinkDto = { id: string; sourceType: string; sourceId: string; targetType: string; targetId: string; anchor: string | null; label: string | null; createdAt: string | null; targetTitle: string | null }

export type RecordDiffItem = { recordId: string | null; localId: string | null; matchValue: string | null; feishuFields: any | null; localFields: any | null }

/**
 * 文件夹命名设置（三项均可选，缺省项跳过不写库——与原 Value 版语义一致）
 */
export type FolderNamingSettingsInput = { folderNamingDateFormat: string | null; folderNamingCaseNoFormat: string | null; folderNamingFileFormat: string | null }

/**
 * 独立日程行（与投影 CalendarEvent 分离；投影时合并进月历数据）（B1 类型化）
 */
export type CalendarEventRow = { id: string; title: string; eventDate: string; startTime: string | null; endTime: string | null; allDay: boolean; color: string | null; location: string | null; notes: string | null; caseId: string | null; taskId: string | null }

/**
 * 收件箱列表项（B1 类型化：返回侧 Value → 强类型）
 * 
 * 空值口径：title/contentText/aiCategory/aiConfidence/sourcePath/userCategory/createdAt
 * 在 SQL 层 COALESCE 归一为 '' / 0（前端手写契约按非空建模；null 与 ''
 * 在展示层真值判断等价），其余可空字段保持 Option。
 */
export type InboxItemDto = { id: string; sourceType: string; sourcePath: string; sourceUrl: string | null; sourceTime: string | null; title: string; contentText: string; aiCategory: string; aiConfidence: number; aiExtracted: any | null; aiSuggestedCaseId: string | null; status: string; userCategory: string; linkedCaseId: string | null; createdAt: string; processedAt: string | null }

/**
 * 实际注入成功的引用（供 UI 展示引用来源）
 */
export type UsedRef = { kind: string; id: string; title: string }

/**
 * 最近活动条目
 */
export type RecentActivity = { eventType: string; title: string; detail: string | null; eventDate: string; caseId: string; caseName: string }

/**
 * 差异行
 */
export type DiffLineDto = { type: string; line: number; text: string }

/**
 * 知识条目主体
 */
export type KnowledgeItemDto = { id: string; title: string; category: string; content: string; tags: string | null; sourceType: string | null; linkedCaseId: string | null; parentId: string | null; blockType: string | null; createdAt: string | null; updatedAt: string | null }

/**
 * 关联案件（含案件摘要信息）
 */
export type RelatedCase = { relationId: string; relationType: string; label: string | null; caseId: string; caseName: string; caseNo: string | null; caseStatus: string | null; clientName: string; track: string }

/**
 * Schema 比较结果
 */
export type SchemaDiff = { feishuOnly: FieldDiffItem[]; localOnly: FieldDiffItem[]; typeConflict: FieldDiffItem[]; mapped: FieldDiffItem[] }

/**
 * 补同步结果
 */
export type CalendarSyncReport = { total: number; synced: number; failed: number; skipped: number }

/**
 * 版本历史项
 */
export type KnowledgeVersionDto = { id: string; content: string; changedAt: string | null; changeReason: string | null }

export type TaskTemplate = { id: string; name: string; triggerType: string | null; tasksJson: string; caseTypes: string | null; enabled: boolean; createdAt: string | null }

/**
 * 案件类型差异化评估指标（B1 类型化）
 */
export type CaseTypeMetrics = { caseId: string; caseType: string; metrics: any }

/**
 * 更新领域输入（⚠️ A1-2 语义：description/icon 直接赋值——None 即清空；
 * name/sort_order 为 COALESCE 保留语义。前端须整组提交。）
 */
export type UpdateAreaInput = { name: string | null; description: string | null; icon: string | null; sortOrder: number | null }

export type BackupFile = { filename: string; sizeBytes: number; modifiedAt: string; sha256: string | null; verified: boolean }

/**
 * 三态 PATCH 字段：
 * - `Unset`: 请求中未提供该字段（保持数据库原值，不参与 UPDATE SET）
 * - `Null`: 请求中显式提供了 null（在 UPDATE SET 中置为 NULL）
 * - `Value(T)`: 请求中提供了具体值（在 UPDATE SET 中更新为该值）
 */
export type PatchField<T> = "Unset" | "Null" | { Value: T }

export type FeishuConfigStatus = { configured: boolean; appId: string | null }

/**
 * 待确认写记录
 */
export type McpPendingWrite = { id: string; tool: string; arguments: string; status: string; result: string | null; createdAt: string | null; resolvedAt: string | null }

/**
 * 导入结果
 */
export type ImportResult = { total: number; created: number; updated: number; skipped: number; errors: string[] }

/**
 * 图谱边
 */
export type GraphEdgeDto = { source: string; target: string; type: string }

export type ImportReport = { cases: number; logs: number; hearings: number; tasks: number; officials: number; errors: string[] }

/**
 * 文件夹命名设置输出（缺省键以 null 呈现，前端按 ?? 默认值消费）
 */
export type FolderNamingSettingsOutput = { folderNamingDateFormat: string | null; folderNamingCaseNoFormat: string | null; folderNamingFileFormat: string | null }

export type HearingDto = { id: string; caseId: string; hearingRecord: string; hearingName: string | null; hearingDate: string; venue: string | null; attendees: string | null; judges: string | null; court: string | null; caseLevel: string | null; contactInfo: string | null; actualStatus: string | null; createdAt: string | null }

/**
 * 前端传入的引用（kind ∈ file / knowledge / task / case）
 */
export type ContextRef = { kind: string; id: string }

/**
 * 命令路由信息
 */
export type CommandRoute = { commandName: string; routeType: string; description: string; requiresConfirmation: boolean; minConfirmLevel: string }

/**
 * 图谱节点
 */
export type GraphNodeDto = { id: string; name: string; type: string; category: string | null }

export type SmartRuleApplyResult = { fileId: string; matchedRules: string[]; actionsApplied: string[] }

/**
 * 版本 vs 当前 对比结果
 */
export type KnowledgeDiffCurrentResult = { version: VersionMetaDto; currentContent: string; diffs: DiffLineDto[] }

export type DeadlineRuleDto = { id: string; track: string; ruleName: string; legalBasis: string; triggerField: string; offsetValue: number; offsetUnit: string; calcMethod: string; procedureTypes: string | null; deadlineSource: string; autoCalculate: boolean; priority: number }

export type FactNodeDto = { id: string; whiteboardId: string; fileId: string | null; fileName: string | null; page: number | null; excerpt: string; note: string | null; x: number; y: number; createdAt: string | null; updatedAt: string | null }

export type DeadlineRuleAuditDto = { id: string; ruleId: string; action: string; beforeJson: string | null; afterJson: string | null; actor: string; createdAt: string | null }

/**
 * 领域统计
 */
export type AreaStatsDto = { areaId: string; areaName: string; totalTasks: number; completedTasks: number; pendingTasks: number; totalCases: number }

/**
 * 案件导入报告
 */
export type CaseImportReport = { totalRowsProcessed: number; createdCount: number; updatedCount: number; skippedCount: number; failedCount: number; errors: string[]; importedCaseIds: string[] }

export type TodayKpis = { todayEvents: number; dueToday: number; waitingOverdue: number; reviewDue: number }

export type TaskFilter = { completed: boolean | null; caseId: string | null; areaId: string | null; taskType: string | null; startBucket: string | null }

export type DeadlineResult = { ruleId: string | null; ruleName: string; dueDate: string; daysLeft: number; urgency: string; deadlineSource: string; legalBasis: string | null; caseId: string; caseName: string }

/**
 * 关系记录
 */
export type CaseRelation = { id: string; sourceCaseId: string; targetCaseId: string; relationType: string; label: string | null; createdAt: string | null }

/**
 * 文件夹模板输入（directories 保持自由 JSON 结构）
 */
export type FolderTemplateInput = { id: string | null; name: string | null; caseType: string | null; directories: any | null; fileNaming: any | null }

export type QuickRecommendation = { action: string; targetCaseId: string | null; targetCaseName: string | null; targetFolder: string | null; intent: any | null; reason: string }

/**
 * 模板列表响应
 */
export type TemplateListResponse = { templates: DocsyTemplate[]; total: number }

/**
 * 批处理进度
 */
export type InboxProgress = { total: number; processed: number; pending: number }

/**
 * 模板字段定义
 */
export type TemplateField = { name: string; field_type: string; default_value: string | null; required: boolean }

export type ImapAccountConfig = { id: string | null; emailAddress: string; imapServer: string; imapPort: number; username: string; password: string; useTls: boolean; watchFolders: string; filterFrom: string | null; filterSubject: string | null; enabled: boolean }

/**
 * 分表导入报告
 */
export type SubtableImportReport = { targetEntity: string; totalRowsProcessed: number; createdCount: number; linkedCasesCount: number; unlinkedCount: number; failedCount: number; errors: string[] }

/**
 * 案件数据结构
 */
export type Case = { id: string; track: string; caseName: string; caseNo: string | null; internalNo: string | null; causeAction: string | null; clientName: string; ourRole: string | null; opponentName: string; opponentRole: string | null; opponentFirm: string | null; opponentAgent: string | null; court: string | null; judgePanel: string | null; clerk: string | null; attorneys: string | null; caseLevel: string | null; caseStatus: string | null; caseProgress: string | null; caseResult: string | null; patentName: string | null; patentAppNo: string | null; procedureType: string | null; filingDate: string | null; complaintReceivedDate: string | null; trialDate: string | null; trial2Date: string | null; trial3Date: string | null; verdictType: string | null; verdictDate: string | null; stayDate: string | null; reliefDeadline: string | null; petitionerFirstInvalid: string | null; petitionerSuppDeadline: string | null; petitionerSubmitDate: string | null; petitionerReceivedDate: string | null; petitionerReplyDeadline: string | null; patenteeReceivedDate: string | null; patenteeStatementDeadline: string | null; patenteeReceivedSuppDate: string | null; patenteeSuppDeadline: string | null; patenteeSubmitSuppDate: string | null; caseRoute: string | null; civilStatus: string | null; invalidationStatus: string | null; adminStatus: string | null; invalidationDecisionDate: string | null; invalidationDecisionType: string | null; adminFilingDate: string | null; adminVerdictDate: string | null; adminTrial2Date: string | null; folderPath: string | null; folderTemplateId: string | null; lastDocPath: string | null; lastDocAt: string | null; completedText: string | null; notes: string | null; createdAt: string | null; updatedAt: string | null; deadlineUrgency?: string | null }

export type MonthTrendPoint = { month: string; created: number; completed: number }

/**
 * 工作表摘要信息
 */
export type SheetInfo = { name: string; rowCount: number; columnCount: number }

/**
 * 字段分组项（B1 类型化）
 */
export type FieldGroupItem = { id: string; columnName: string; label: string; fieldType: string; options: any; required: boolean; sortOrder: number }

export type CaseFile = { id: string; caseId: string; fileName: string; filePath: string; fileSize: number | null; fileType: string | null; category: string; subCategory: string | null; createdAt: string | null }

/**
 * Docsy 模板信息
 */
export type DocsyTemplate = { id: string; name: string; path: string; category: string; field_count: number; fields: TemplateField[]; description: string }

/**
 * ai_chat 返回体（K-3 归因）：content + 本次对话的 ai_runs 关联键 + @ 引用来源
 */
export type AiChatResult = { content: string; runId: string | null; usedRefs: UsedRef[] }

/**
 * 工作表探测与预览结果
 */
export type ExcelInspectResult = { sheetName: string; totalRows: number; detectedHeaderRow: number; columns: ColumnMappingRecommendation[]; previewRows: { [key: string]: any }[] }

/**
 * 创建知识条目输入（B1 类型化；全部可选，缺省口径与原 Value 版一致）
 */
export type CreateKnowledgeInput = { blockType: string; title: string; category: string; content: string; tags: string | null; sourceType: string | null; sourceId: string | null; linkedCaseId: string | null; lawName: string | null; articleNo: string | null; effectiveDate: string | null; status: string; parentId: string | null }

export type AppNotification = { id: string; type: string; title: string; body: string | null; payloadJson: string | null; createdAt: string | null; readAt: string | null }

/**
 * 条目 + 块树
 */
export type KnowledgeWithBlocksDto = { item: KnowledgeItemDto; blocks: KnowledgeTreeBlockDto[] }

/**
 * 节假日解析结果（B1 类型化）
 */
export type HolidayNotice = { year: number; holidays: string[]; workdays: string[] }

export type FeishuTableMeta = { tableId: string; name: string; revision: number | null }

/**
 * 新建领域输入
 */
export type CreateAreaInput = { name: string; description?: string | null; icon?: string | null; sortOrder?: number }

/**
 * 全文检索命中项
 */
export type SearchKnowledgeDto = { id: string; title: string; category: string; content: string; tags: string | null; lawName: string | null; articleNo: string | null }

/**
 * AI 操作提案数据结构（P0-2：服务端不可绕过授权网关）
 */
export type AiProposal = { id: string; toolName: string; targetEntityType: string; targetEntityId: string | null; preStateHash: string | null; payloadJson: string; authToken: string; expiresAt: string; status: string; createdAt: string; executedAt: string | null }

export type CaseStats = { total: number; active: number; closed: number; byTrack: ([string, number])[]; byClient: ([string, number])[] }

/**
 * 列映射推荐
 */
export type ColumnMappingRecommendation = { columnIndex: number; excelHeader: string; sampleValues: string[]; suggestedField: string | null; confidence: number }

/**
 * 提案预览：proposal 全字段 + 目标实体当前状态 + 字段级 Diff
 */
export type ProposalPreviewDto = { proposal: AiProposal; targetEntityName: string | null; currentState: any | null; fieldDiffs: ProposalFieldDiff[] }

/**
 * 对话消息：role ∈ { system, user, assistant }（tool 结果由前端拼为 user 前缀）
 */
export type ChatMessage = { role: string; content: string }

export type AiConfig = { mode: string; apiUrl: string | null; apiKey: string | null; model: string | null; dailyLimit: number | null }

export type SmartRuleDto = { id: string; name: string; enabled: boolean; matchField: string; matchPattern: string; actionType: string; actionPayload: string; createdAt: string | null; updatedAt: string | null }

export type WhiteboardEdgeDto = { id: string; whiteboardId: string; sourceNodeId: string; targetNodeId: string; createdAt: string | null }

/**
 * 知识图谱
 */
export type KnowledgeGraphDto = { nodes: GraphNodeDto[]; edges: GraphEdgeDto[] }

/**
 * 分表导入配置 (支持关联任务、庭审、办案日志分表)
 */
export type SubtableImportConfig = { targetEntity: string; headerRow: number; columnMappings: { [key: number]: string }; forwardFillColumns: number[] }

export type TimelineEvent = { id: string; sourceTable: string; sourceId: string; eventDate: string; eventType: string; title: string; detail: string | null; icon: string; color: string }

