// This file has been generated by Specta. DO NOT EDIT.

export type ReminderLogEntry = { id: string; ruleId: string; caseId: string | null; taskId: string | null; channel: string; message: string; level: string | null; status: string; sentAt: string | null }

/**
 * 列表查询结果
 */
export type CaseListResult = { items: Case[]; total: number; page: number; perPage: number }

export type SyncStatus = { webdavConnected: boolean; webdavUrl: string; lastSyncAt: string | null; deviceVersion: number; remoteEtag: string | null; pendingChanges: boolean }

/**
 * Schema 比较结果
 */
export type SchemaDiff = { feishuOnly: FieldDiffItem[]; localOnly: FieldDiffItem[]; typeConflict: FieldDiffItem[]; mapped: FieldDiffItem[] }

export type ReminderRule = { id: string; name: string; triggerType: string; triggerValue: number | null; channels: string; messageTemplate: string | null; caseTypes: string | null; enabled: boolean; createdAt: string | null }

/**
 * 最近活动条目
 */
export type RecentActivity = { eventType: string; title: string; detail: string | null; eventDate: string; caseId: string; caseName: string }

export type FeishuSyncReport = { pulled: number; pushed: number; created: number; updated: number; skipped: number; errors: string[]; syncedAt: string }

/**
 * ai_chat 返回体（K-3 归因）：content + 本次对话的 ai_runs 关联键
 */
export type AiChatResult = { content: string; runId: string | null }

/**
 * 列表查询过滤条件
 */
export type CaseFilter = { track: string | null; client: string | null; court: string | null; status: string | null; search: string | null; dateFrom: string | null; dateTo: string | null; sortBy: string | null; page: number | null; perPage: number | null; caseRoute: string | null; civilStatus: string | null; invalidationStatus: string | null; adminStatus: string | null }

export type FieldDiffItem = { feishuField: string | null; feishuType: string | null; feishuTypeCode: number | null; localColumn: string | null; localType: string | null; status: string }

export type SyncResult = { direction: string; success: boolean; message: string; conflict: boolean; localEtag: string | null; remoteEtag: string | null }

/**
 * 检索结果条目
 */
export type SearchResult = { id: string; title: string; category: string; content: string; tags: string | null; lawName: string | null; articleNo: string | null; score: number; source: string }

/**
 * 渲染结果响应
 */
export type RenderResponse = { html: string; text: string; used_fields: { [key: string]: string }; missing_fields: string[] }

/**
 * AI 处理结果（分类 + 置信度 + 抽取 + 自动路由动作）
 */
export type ProcessedInboxResult = { category: string; confidence: number; suggestedCaseId: string | null; caseNo: string | null; extracted: any | null; routeActions: any[] }

/**
 * 任务列表项（B1 类型化：返回侧 Value → 强类型；字段与前端手写 Task 契约一致）
 */
export type TaskDto = { id: string; caseId: string | null; taskName: string; description: string | null; createdDate: string; deadline: string | null; priority: string | null; completed: number; assignee: string | null; finishNote: string | null; taskType: string; startDate: string | null; dueDate: string | null; waitingFor: string | null; followUpDate: string | null; context: string | null; flagged: number; sequential: number; blocked: number; sequenceOrder: number; startBucket: string; todayIndex: number; estimatedMinutes: number | null; actualMinutes: number | null; isOverdue: number; dueSoon: number; lastReviewDate: string | null; nextReviewDate: string | null; areaId: string | null; knowledgeId: string | null }

export type Draft = { id: string; case_id: string | null; title: string; content: string | null; template_path: string | null; status: string; version: number; created_at: string; updated_at: string }

export type CaseFile = { id: string; caseId: string; fileName: string; filePath: string; fileSize: number | null; fileType: string | null; category: string; subCategory: string | null; createdAt: string | null }

/**
 * 待确认写记录
 */
export type McpPendingWrite = { id: string; tool: string; arguments: string; status: string; result: string | null; createdAt: string | null; resolvedAt: string | null }

/**
 * 分级预警结果
 */
export type DeadlineWarning = { deadlineId: string; caseId: string; caseName: string; deadlineName: string; dueDate: string; daysLeft: number; level: string; levelLabel: string; levelColor: string; message: string }

/**
 * 收件箱列表项（B1 类型化：返回侧 Value → 强类型）
 * 
 * 空值口径：title/contentText/aiCategory/aiConfidence/sourcePath/userCategory/createdAt
 * 在 SQL 层 COALESCE 归一为 '' / 0（前端手写契约按非空建模；null 与 ''
 * 在展示层真值判断等价），其余可空字段保持 Option。
 */
export type InboxItemDto = { id: string; sourceType: string; sourcePath: string; sourceUrl: string | null; sourceTime: string | null; title: string; contentText: string; aiCategory: string; aiConfidence: number; aiExtracted: any | null; aiSuggestedCaseId: string | null; status: string; userCategory: string; linkedCaseId: string | null; createdAt: string; processedAt: string | null }

/**
 * 关联案件（含案件摘要信息）
 */
export type RelatedCase = { relationId: string; relationType: string; label: string | null; caseId: string; caseName: string; caseNo: string | null; caseStatus: string | null; clientName: string; track: string }

export type AiConfig = { mode: string; apiUrl: string | null; apiKey: string | null; model: string | null; dailyLimit: number | null }

/**
 * 比较飞书记录 vs 本地记录
 */
export type RecordDiff = { same: RecordDiffItem[]; feishuOnly: RecordDiffItem[]; localOnly: RecordDiffItem[]; conflict: RecordDiffItem[] }

/**
 * 补同步结果
 */
export type CalendarSyncReport = { total: number; synced: number; failed: number; skipped: number }

/**
 * 命令路由信息
 */
export type CommandRoute = { commandName: string; routeType: string; description: string; requiresConfirmation: boolean; minConfirmLevel: string }

export type TaskTemplate = { id: string; name: string; triggerType: string | null; tasksJson: string; caseTypes: string | null; enabled: boolean; createdAt: string | null }

/**
 * 导出结果响应
 */
export type ExportResponse = { output_path: string; file_size: number; exported_at: string }

/**
 * 全局搜索结果项（轻量列）
 */
export type SearchTaskDto = { id: string; taskName: string; dueDate: string | null; completed: number; startBucket: string | null }

/**
 * 仪表盘聚合数据
 */
export type DashboardStats = { activeCount: number; totalCount: number; closedCount: number; deadlineWarnings: DeadlineResult[]; recentActivities: RecentActivity[]; byTrack: ([string, number])[] }

/**
 * 对话消息：role ∈ { system, user, assistant }（tool 结果由前端拼为 user 前缀）
 */
export type ChatMessage = { role: string; content: string }

export type TaskFilter = { completed: boolean | null; caseId: string | null; areaId: string | null; taskType: string | null; startBucket: string | null }

export type DeadlineResult = { ruleId: string | null; ruleName: string; dueDate: string; daysLeft: number; urgency: string; deadlineSource: string; legalBasis: string | null; caseId: string; caseName: string }

/**
 * 关系记录
 */
export type CaseRelation = { id: string; sourceCaseId: string; targetCaseId: string; relationType: string; label: string | null; createdAt: string | null }

/**
 * 模板列表响应
 */
export type TemplateListResponse = { templates: DocsyTemplate[]; total: number }

/**
 * 批处理进度
 */
export type InboxProgress = { total: number; processed: number; pending: number }

/**
 * 模板字段定义
 */
export type TemplateField = { name: string; field_type: string; default_value: string | null; required: boolean }

export type ImapAccountConfig = { id: string | null; emailAddress: string; imapServer: string; imapPort: number; username: string; password: string; useTls: boolean; watchFolders: string; filterFrom: string | null; filterSubject: string | null; enabled: boolean }

export type QuickRecommendation = { action: string; targetCaseId: string | null; targetCaseName: string | null; targetFolder: string | null; intent: any | null; reason: string }

/**
 * 案件数据结构
 */
export type Case = { id: string; track: string; caseName: string; caseNo: string | null; internalNo: string | null; causeAction: string | null; clientName: string; ourRole: string | null; opponentName: string; opponentRole: string | null; opponentFirm: string | null; opponentAgent: string | null; court: string | null; judgePanel: string | null; clerk: string | null; attorneys: string | null; caseLevel: string | null; caseStatus: string | null; caseProgress: string | null; caseResult: string | null; patentName: string | null; patentAppNo: string | null; procedureType: string | null; filingDate: string | null; complaintReceivedDate: string | null; trialDate: string | null; trial2Date: string | null; trial3Date: string | null; verdictType: string | null; verdictDate: string | null; stayDate: string | null; reliefDeadline: string | null; petitionerFirstInvalid: string | null; petitionerSuppDeadline: string | null; petitionerSubmitDate: string | null; petitionerReceivedDate: string | null; petitionerReplyDeadline: string | null; patenteeReceivedDate: string | null; patenteeStatementDeadline: string | null; patenteeReceivedSuppDate: string | null; patenteeSuppDeadline: string | null; patenteeSubmitSuppDate: string | null; caseRoute: string | null; civilStatus: string | null; invalidationStatus: string | null; adminStatus: string | null; invalidationDecisionDate: string | null; invalidationDecisionType: string | null; adminFilingDate: string | null; adminVerdictDate: string | null; adminTrial2Date: string | null; folderPath: string | null; folderTemplateId: string | null; lastDocPath: string | null; lastDocAt: string | null; completedText: string | null; notes: string | null; createdAt: string | null; updatedAt: string | null; deadlineUrgency?: string | null }

export type CaseStats = { total: number; active: number; closed: number; byTrack: ([string, number])[]; byClient: ([string, number])[] }

export type RecordDiffItem = { recordId: string | null; localId: string | null; matchValue: string | null; feishuFields: any | null; localFields: any | null }

/**
 * Docsy 模板信息
 */
export type DocsyTemplate = { id: string; name: string; path: string; category: string; field_count: number; fields: TemplateField[]; description: string }

export type ImportReport = { cases: number; logs: number; hearings: number; tasks: number; officials: number; errors: string[] }

/**
 * 即时判断结果
 */
export type QuickJudgeResult = { category: string; confidence: number; strength: string; recommendations: QuickRecommendation[]; aiAvailable: boolean; aiAnalyzed: boolean }

export type TimelineEvent = { id: string; sourceTable: string; sourceId: string; eventDate: string; eventType: string; title: string; detail: string | null; icon: string; color: string }

