"""Generate the Vue icon family from the supplied Judicial Docket SVGs."""
import json,re
from pathlib import Path
root=Path(__file__).resolve().parents[1]
icons=root/'src/shared/icons'
paths={p.stem:re.sub(r'^<svg[^>]*>|</svg>\s*$','',p.read_text().strip()).strip() for p in (root/'designs/casy-ui-upgrade/icons/svg').glob('*.svg')}
paths.update(json.loads((icons/'geometry.json').read_text()))
entries=json.loads((icons/'aliases.json').read_text())
body="// Generated by scripts/generate-icons.py; trusted local SVG paths only.\nimport { defineComponent, h } from 'vue'\n\n"
body+='export const glyphs = '+json.dumps(paths,ensure_ascii=False,indent=2)+' as const\n'
body+="export type DocketIconName = keyof typeof glyphs\n"
body+="export function docketIcon(name: DocketIconName) { return defineComponent({ name: 'DocketIcon_' + name, setup: (_, { attrs }) => () => h('svg', { ...attrs, width: '1em', height: '1em', viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor', 'stroke-width': 1.5, 'stroke-linecap': 'round', 'stroke-linejoin': 'round', 'aria-hidden': true, focusable: false, innerHTML: glyphs[name] }) }) }\n"
for alias,name in sorted(entries.items()):body+=f"export const {alias} = docketIcon('{name}')\n"
body+="export const BrandSeal = docketIcon('brand-seal')\nexport const Waiting = docketIcon('waiting')\n"
(icons/'index.ts').write_text(body)
print('Generated',len(paths),'glyphs;',len(entries),'compatibility exports')
