//! specta TS 绑定导出（D-3）
//!
//! 运行：`cargo test export_bindings`（在 src-tauri/ 下）；
//! 产物 src/types/bindings.ts 为生成物，禁止手改。

#[cfg(test)]
#[test]
fn export_ts_bindings() {
    let conf =
        specta::ts::ExportConfiguration::new().bigint(specta::ts::BigIntExportBehavior::Number);
    specta::export::ts_with_cfg("../src/types/bindings.ts", &conf).expect("specta TS 导出失败");
    // Specta 1 sorts by type ID, which varies between binaries/platforms.
    let registry = specta::export::TYPES.lock().unwrap();
    let mut types: Vec<_> = registry.0.values().filter_map(Option::as_ref)
        .filter(|datatype| datatype.export.unwrap_or(true)).collect();
    types.sort_by_key(|datatype| datatype.name);
    let mut output = "// This file has been generated by Specta. DO NOT EDIT.\n\n".to_string();
    for datatype in types {
        output.push_str(&specta::ts::export_datatype(&conf, datatype).unwrap());
        output.push_str("\n\n");
    }
    let output=output.split('\n').map(str::trim_end).collect::<Vec<_>>().join("\n");
    std::fs::write("../src/types/bindings.ts", output).unwrap();
}
