// Generated by scripts/generate-icons.py; trusted local SVG paths only.
import { defineComponent, h } from 'vue'

export const glyphs = {
  "search": "<circle cx=\"11\" cy=\"11\" r=\"6.2\"/>\n  <path d=\"M15.5 15.5L20 20\"/>",
  "tasks": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2.5\"/>\n  <path d=\"M8 12.2l2.4 2.4L16 9.4\"/>",
  "brief": "<path d=\"M5 5.5h11.5c.8 0 1.5.7 1.5 1.5v12c0 .8-.7 1.5-1.5 1.5H5c-.8 0-1.5-.7-1.5-1.5V7c0-.8.7-1.5 1.5-1.5z\"/>\n  <path d=\"M7.5 9h6M7.5 12.5h6M7.5 16h4\"/>\n  <path d=\"M18 8.5h1.5c.8 0 1.5.7 1.5 1.5v8\"/>",
  "inbox": "<path d=\"M3.5 13.5h4.2l1.2 2.2h6.2l1.2-2.2h4.2\"/>\n  <path d=\"M3.5 13.5 6 6.2c.3-.8 1-1.2 1.8-1.2h8.4c.8 0 1.5.4 1.8 1.2l2.5 7.3\"/>\n  <path d=\"M3.5 13.5v3.8c0 .9.7 1.7 1.7 1.7h13.6c1 0 1.7-.8 1.7-1.7v-3.8\"/>",
  "file": "<path d=\"M7.5 3.8h6.8L18.5 8v12.2H7.5V3.8z\"/>\n  <path d=\"M14 3.8V8h4.5\"/>\n  <path d=\"M9.8 12.5h6.4M9.8 16h4.2\"/>",
  "dossier": "<path d=\"M3.5 8.2h6.2l1.5 1.8h9.3c.8 0 1.5.7 1.5 1.5v7.8c0 .8-.7 1.5-1.5 1.5H3.5c-.8 0-1.5-.7-1.5-1.5V9.7c0-.8.7-1.5 1.5-1.5z\"/>\n  <path d=\"M2 12.8h20\"/>\n  <path d=\"M6.2 8.2V6.5c0-.8.7-1.5 1.5-1.5h3.4l1.3 1.6\"/>",
  "brand-seal": "<circle cx=\"12\" cy=\"12\" r=\"8.2\"/>\n  <circle cx=\"12\" cy=\"12\" r=\"5.6\"/>\n  <path d=\"M12 7.8v8.4\"/>\n  <path d=\"M9.2 10.2h5.6\"/>\n  <path d=\"M9.2 13.8h5.6\"/>",
  "chevron-right": "<path d=\"M9.5 6.5l5.5 5.5-5.5 5.5\"/>",
  "link": "<path d=\"M10.2 13.8a3.5 3.5 0 0 0 5 0l3-3a3.5 3.5 0 0 0-5-5l-1.2 1.2\"/>\n  <path d=\"M13.8 10.2a3.5 3.5 0 0 0-5 0l-3 3a3.5 3.5 0 0 0 5 5l1.2-1.2\"/>",
  "settings": "<circle cx=\"12\" cy=\"12\" r=\"3\"/>\n  <path d=\"M12 3.8v2.2M12 18v2.2M3.8 12h2.2M18 12h2.2M6.2 6.2l1.6 1.6M16.2 16.2l1.6 1.6M17.8 6.2l-1.6 1.6M7.8 16.2l-1.6 1.6\"/>",
  "projects": "<rect x=\"7.5\" y=\"3.8\" width=\"12.2\" height=\"4.2\" rx=\"1\"/>\n  <rect x=\"4.3\" y=\"9.9\" width=\"12.2\" height=\"4.2\" rx=\"1\"/>\n  <rect x=\"7.5\" y=\"16\" width=\"12.2\" height=\"4.2\" rx=\"1\"/>",
  "reminder": "<path d=\"M6.5 10.2a5.5 5.5 0 0 1 11 0c0 3.2.8 4.6 1.5 5.5H5c.7-.9 1.5-2.3 1.5-5.5z\"/>\n  <path d=\"M10 18.2a2.2 2.2 0 0 0 4 0\"/>\n  <path d=\"M12 5.2V3.8\"/>",
  "archive": "<rect x=\"3.5\" y=\"4.5\" width=\"17\" height=\"4.2\" rx=\"1\"/>\n  <path d=\"M5 8.7v9.8c0 .8.7 1.5 1.5 1.5h11c.8 0 1.5-.7 1.5-1.5V8.7\"/>\n  <path d=\"M9.5 12.5h5\"/>",
  "knowledge": "<path d=\"M4.5 5.2c2.4-.8 4.8-.8 7.5.6v13c-2.7-1.4-5.1-1.4-7.5-.6V5.2z\"/>\n  <path d=\"M19.5 5.2c-2.4-.8-4.8-.8-7.5.6v13c2.7-1.4 5.1-1.4 7.5-.6V5.2z\"/>\n  <path d=\"M12 5.8v13\"/>",
  "dashboard": "<rect x=\"3.5\" y=\"3.5\" width=\"7.2\" height=\"7.2\" rx=\"1.2\"/>\n  <rect x=\"13.3\" y=\"3.5\" width=\"7.2\" height=\"7.2\" rx=\"1.2\"/>\n  <rect x=\"3.5\" y=\"13.3\" width=\"7.2\" height=\"7.2\" rx=\"1.2\"/>\n  <path d=\"M14.5 18.5v-3.2M17 18.5v-5.2M19.5 18.5v-2\"/>",
  "plus": "<path d=\"M12 5v14M5 12h14\"/>",
  "check": "<path d=\"M5 12.5l4.2 4.2L19 7.8\"/>",
  "relation": "<circle cx=\"6\" cy=\"7\" r=\"2.2\"/>\n  <circle cx=\"18\" cy=\"7\" r=\"2.2\"/>\n  <circle cx=\"12\" cy=\"17\" r=\"2.2\"/>\n  <path d=\"M8 8.2l2.8 6.4M16 8.2l-2.8 6.4M8.2 7h7.6\"/>",
  "today": "<circle cx=\"12\" cy=\"10\" r=\"3.25\"/>\n  <path d=\"M12 3.5v1.2\"/>\n  <path d=\"M5.5 10h1.1\"/>\n  <path d=\"M17.4 10h1.1\"/>\n  <path d=\"M4 16.5h16\"/>\n  <path d=\"M6.5 19.5h11\"/>",
  "cases": "<rect x=\"3.5\" y=\"7.5\" width=\"17\" height=\"11.5\" rx=\"1.5\"/>\n  <path d=\"M9 7.5V6.2c0-.7.5-1.2 1.2-1.2h3.6c.7 0 1.2.5 1.2 1.2v1.3\"/>\n  <path d=\"M3.5 12.5h17\"/>\n  <path d=\"M10.5 12.5v1.5h3v-1.5\"/>",
  "ai": "<path d=\"M12 3.8l1.2 3.2L16.4 8.2l-3.2 1.2L12 12.6l-1.2-3.2L7.6 8.2l3.2-1.2L12 3.8z\"/>\n  <path d=\"M18.2 13.2l.7 1.8 1.8.7-1.8.7-.7 1.8-.7-1.8-1.8-.7 1.8-.7.7-1.8z\"/>\n  <path d=\"M6.5 14.5l.6 1.5 1.5.6-1.5.6-.6 1.5-.6-1.5-1.5-.6 1.5-.6.6-1.5z\"/>",
  "risk": "<path d=\"M12 4.2L21 19.2H3L12 4.2z\"/>\n  <path d=\"M12 10.2v4.2\"/>\n  <path d=\"M12 16.8h.01\"/>",
  "star": "<path d=\"M12 3.8l2.4 5 5.5.8-4 3.8.9 5.5L12 16.4 7.2 18.9l.9-5.5-4-3.8 5.5-.8L12 3.8z\"/>",
  "seal": "<circle cx=\"12\" cy=\"12\" r=\"8.2\"/>\n  <circle cx=\"12\" cy=\"12\" r=\"5.6\"/>\n  <path d=\"M12 7.8v8.4\"/>\n  <path d=\"M9.2 10.2h5.6\"/>\n  <path d=\"M9.2 13.8h5.6\"/>",
  "capture": "<path d=\"M4.5 8.5V6.2c0-.9.7-1.7 1.7-1.7H8.5\"/>\n  <path d=\"M15.5 4.5h2.3c.9 0 1.7.7 1.7 1.7v2.3\"/>\n  <path d=\"M19.5 15.5v2.3c0 .9-.7 1.7-1.7 1.7h-2.3\"/>\n  <path d=\"M8.5 19.5H6.2c-.9 0-1.7-.7-1.7-1.7v-2.3\"/>\n  <path d=\"M12 8.5v7M8.5 12h7\"/>",
  "waiting": "<path d=\"M7.5 3.8h9\"/>\n  <path d=\"M7.5 20.2h9\"/>\n  <path d=\"M8.5 3.8c0 4.2 3.5 5.2 3.5 8.2 0 3-3.5 4-3.5 8.2\"/>\n  <path d=\"M15.5 3.8c0 4.2-3.5 5.2-3.5 8.2 0 3 3.5 4 3.5 8.2\"/>",
  "clock": "<circle cx=\"12\" cy=\"12\" r=\"8\"/>\n  <path d=\"M12 7.5V12l3 2\"/>",
  "sync": "<path d=\"M6.5 8.5h10.2a3.5 3.5 0 0 1 3.5 3.5\"/>\n  <path d=\"M17.5 15.5H7.3A3.5 3.5 0 0 1 3.8 12\"/>\n  <path d=\"M6.5 8.5l-2.7-2.7M6.5 8.5l2.2-2.5\"/>\n  <path d=\"M17.5 15.5l2.7 2.7M17.5 15.5l-2.2 2.5\"/>",
  "drafting": "<path d=\"M14.8 4.4l4.8 4.8\"/>\n  <path d=\"M13.2 5.6l5.2 5.2-7.8 7.8H5.4v-5.2l7.8-7.8z\"/>\n  <path d=\"M11.4 8.6l4 4\"/>",
  "filter": "<path d=\"M4 5.5h16l-6.2 7.2v5.3l-3.6 1.8v-7.1L4 5.5z\"/>",
  "calendar": "<rect x=\"3.8\" y=\"5.5\" width=\"16.4\" height=\"14.2\" rx=\"1.5\"/>\n  <path d=\"M3.8 9.5h16.4\"/>\n  <path d=\"M8 3.8v3.2\"/>\n  <path d=\"M16 3.8v3.2\"/>\n  <path d=\"M8.2 13h.01M12 13h.01M15.8 13h.01M8.2 16.5h.01M12 16.5h.01\"/>",
  "ocr": "<path d=\"M7.5 4.5h9c.8 0 1.5.7 1.5 1.5v12c0 .8-.7 1.5-1.5 1.5h-9c-.8 0-1.5-.7-1.5-1.5V6c0-.8.7-1.5 1.5-1.5z\"/>\n  <path d=\"M9 8.5h6M9 12h6M9 15.5h3.5\"/>\n  <path d=\"M4 9.5h1.5M4 14.5h1.5M18.5 9.5H20M18.5 14.5H20\"/>",
  "close": "<path d=\"m6 6 12 12M18 6 6 18\"/>",
  "minus": "<path d=\"M5 12h14\"/>",
  "delete": "<path d=\"M4 6h16M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7M14 10v7\"/>",
  "edit": "<path d=\"m4 16 11-11 4 4L8 20l-5 1 1-5ZM13 7l4 4\"/>",
  "upload": "<path d=\"M12 16V3m-4 4 4-4 4 4M4 15v6h16v-6\"/>",
  "download": "<path d=\"M12 3v13m-4-4 4 4 4-4M4 16v5h16v-5\"/>",
  "more": "<circle cx=\"5\" cy=\"12\" r=\"1\"/><circle cx=\"12\" cy=\"12\" r=\"1\"/><circle cx=\"19\" cy=\"12\" r=\"1\"/>",
  "user": "<circle cx=\"12\" cy=\"7\" r=\"4\"/><path d=\"M4 21v-2a8 8 0 0 1 16 0v2\"/>",
  "users": "<circle cx=\"9\" cy=\"7\" r=\"3.5\"/><path d=\"M2 21v-3a7 7 0 0 1 14 0v3M17 4a3.5 3.5 0 0 1 0 7M19 14a6 6 0 0 1 3 5v2\"/>",
  "arrow-left": "<path d=\"M20 12H4m6-6-6 6 6 6\"/>",
  "arrow-right": "<path d=\"M4 12h16m-6-6 6 6-6 6\"/>",
  "arrow-up": "<path d=\"M12 20V4m-6 6 6-6 6 6\"/>",
  "arrow-down": "<path d=\"M12 4v16m-6-6 6 6 6-6\"/>",
  "chevron-down": "<path d=\"m5 9 7 7 7-7\"/>",
  "panel-open": "<rect x=\"3\" y=\"3\" width=\"18\" height=\"18\" rx=\"2\"/><path d=\"M9 3v18m4-13 4 4-4 4\"/>",
  "panel-close": "<rect x=\"3\" y=\"3\" width=\"18\" height=\"18\" rx=\"2\"/><path d=\"M9 3v18m8-13-4 4 4 4\"/>",
  "info": "<circle cx=\"12\" cy=\"12\" r=\"9\"/><path d=\"M12 11v6m0-10v.1\"/>",
  "help": "<circle cx=\"12\" cy=\"12\" r=\"9\"/><path d=\"M9 9a3 3 0 1 1 5 2c-2 1-2 2-2 3m0 3v.1\"/>",
  "check-circle": "<circle cx=\"12\" cy=\"12\" r=\"9\"/><path d=\"m7 12 3 3 7-7\"/>",
  "close-circle": "<circle cx=\"12\" cy=\"12\" r=\"9\"/><path d=\"m9 9 6 6m0-6-6 6\"/>",
  "view": "<path d=\"M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z\"/><circle cx=\"12\" cy=\"12\" r=\"3\"/>",
  "hide": "<path d=\"m3 3 18 18M10 5c7-1 12 7 12 7l-3 4M6 6 2 12s4 7 10 7l4-1m-7-9a4 4 0 0 0 6 6\"/>",
  "copy": "<rect x=\"8\" y=\"8\" width=\"13\" height=\"13\" rx=\"2\"/><path d=\"M16 8V3H3v13h5\"/>",
  "attachment": "<path d=\"m8 14 7-7a3 3 0 0 1 4 4L9 21a5 5 0 0 1-7-7L14 2\"/>",
  "location": "<path d=\"M19 9c0 5-7 12-7 12S5 14 5 9a7 7 0 0 1 14 0Z\"/><circle cx=\"12\" cy=\"9\" r=\"2.5\"/>",
  "mail": "<rect x=\"3\" y=\"5\" width=\"18\" height=\"14\" rx=\"2\"/><path d=\"m3 6 9 7 9-7\"/>",
  "chat": "<path d=\"M21 15a3 3 0 0 1-3 3H9l-6 4V6a3 3 0 0 1 3-3h12a3 3 0 0 1 3 3Z\"/><path d=\"M7 8h10M7 12h7\"/>",
  "microphone": "<rect x=\"9\" y=\"2\" width=\"6\" height=\"13\" rx=\"3\"/><path d=\"M5 10v2a7 7 0 0 0 14 0v-2M12 19v3m-4 0h8\"/>",
  "phone": "<path d=\"m7 3 3 5-3 3 6 6 3-3 5 3-1 4C10 22 2 14 3 4Z\"/>",
  "picture": "<rect x=\"3\" y=\"3\" width=\"18\" height=\"18\" rx=\"2\"/><circle cx=\"8\" cy=\"8\" r=\"2\"/><path d=\"m3 18 6-6 4 4 3-3 5 5\"/>",
  "lock": "<rect x=\"5\" y=\"10\" width=\"14\" height=\"11\" rx=\"2\"/><path d=\"M8 10V6a4 4 0 0 1 8 0v4m-4 5v2\"/>",
  "key": "<circle cx=\"8\" cy=\"8\" r=\"5\"/><path d=\"m12 12 9 9m-5-5 3-3m-1 5 3-3\"/>",
  "loading": "<path d=\"M21 12a9 9 0 1 1-9-9\"/>",
  "refresh-left": "<path d=\"M3 4v6h6M3 10a9 9 0 1 1 1 8\"/>",
  "refresh-right": "<path d=\"M21 4v6h-6m6 0a9 9 0 1 0-1 8\"/>",
  "fullscreen": "<path d=\"M3 9V3h6m6 0h6v6m0 6v6h-6m-6 0H3v-6\"/>",
  "zoom-in": "<circle cx=\"10\" cy=\"10\" r=\"7\"/><path d=\"m15 15 6 6M7 10h6m-3-3v6\"/>",
  "zoom-out": "<circle cx=\"10\" cy=\"10\" r=\"7\"/><path d=\"m15 15 6 6M7 10h6\"/>",
  "play": "<path d=\"m7 3 14 9-14 9Z\"/>",
  "power": "<path d=\"M12 2v10M6 5a9 9 0 1 0 12 0\"/>",
  "printer": "<path d=\"M7 8V3h10v5M7 17H3V8h18v9h-4M7 14h10v7H7Zm10-3h1\"/>",
  "building": "<path d=\"M4 21V3h12v18M16 9h4v12M8 7h4M8 11h4M8 15h4M9 21v-3h2v3\"/>",
  "chart": "<path d=\"M3 3v18h18M7 17v-5m5 5V7m5 10V4\"/>",
  "cloud": "<path d=\"M6 19a4 4 0 0 1-1-8 7 7 0 0 1 13-3 5.5 5.5 0 0 1 0 11Z\"/>",
  "list": "<path d=\"M8 5h13M8 12h13M8 19h13M3 5h.1M3 12h.1M3 19h.1\"/>",
  "sort": "<path d=\"M7 3v18m-4-4 4 4 4-4m6 4V3m-4 4 4-4 4 4\"/>",
  "open": "<path d=\"M13 3h8v8m0-8L10 14M9 3H3v18h18v-6\"/>",
  "lightbulb": "<path d=\"M9 18h6m-6 3h6M8 15a7 7 0 1 1 8 0v3H8Z\"/>",
  "compass": "<circle cx=\"12\" cy=\"12\" r=\"9\"/><path d=\"m15 9-2 4-4 2 2-4Z\"/>",
  "folder-add": "<path d=\"M3 5h7l2 3h9v13H3ZM12 12v6m-3-3h6\"/>",
  "file-add": "<path d=\"M4 3h10l6 6v12H4ZM14 3v6h6M12 12v6m-3-3h6\"/>",
  "folder-check": "<path d=\"M3 5h7l2 3h9v13H3Zm5 10 3 3 6-6\"/>"
} as const
export type DocketIconName = keyof typeof glyphs
export function docketIcon(name: DocketIconName) { return defineComponent({ name: 'DocketIcon_' + name, setup: (_, { attrs }) => () => h('svg', { ...attrs, width: '1em', height: '1em', viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor', 'stroke-width': 1.5, 'stroke-linecap': 'round', 'stroke-linejoin': 'round', 'aria-hidden': true, focusable: false, innerHTML: glyphs[name] }) }) }
export const Aim = docketIcon('capture')
export const AlarmClock = docketIcon('reminder')
export const ArrowDown = docketIcon('chevron-down')
export const ArrowLeft = docketIcon('arrow-left')
export const ArrowRight = docketIcon('chevron-right')
export const ArrowRightBold = docketIcon('chevron-right')
export const Avatar = docketIcon('user')
export const Back = docketIcon('arrow-left')
export const Bell = docketIcon('reminder')
export const Bottom = docketIcon('arrow-down')
export const Box = docketIcon('inbox')
export const Briefcase = docketIcon('cases')
export const Calendar = docketIcon('calendar')
export const CaretRight = docketIcon('chevron-right')
export const ChatDotRound = docketIcon('chat')
export const ChatLineRound = docketIcon('chat')
export const ChatLineSquare = docketIcon('chat')
export const ChatSquare = docketIcon('chat')
export const Check = docketIcon('check')
export const Checked = docketIcon('tasks')
export const CircleCheck = docketIcon('check-circle')
export const CircleClose = docketIcon('close-circle')
export const Clock = docketIcon('clock')
export const Close = docketIcon('close')
export const Cloudy = docketIcon('cloud')
export const Collection = docketIcon('knowledge')
export const CollectionTag = docketIcon('brief')
export const Compass = docketIcon('compass')
export const Connection = docketIcon('relation')
export const CopyDocument = docketIcon('copy')
export const Cpu = docketIcon('ai')
export const DataAnalysis = docketIcon('chart')
export const DataBoard = docketIcon('dashboard')
export const Delete = docketIcon('delete')
export const Document = docketIcon('file')
export const DocumentAdd = docketIcon('file-add')
export const DocumentCopy = docketIcon('copy')
export const Download = docketIcon('download')
export const Edit = docketIcon('edit')
export const EditPen = docketIcon('drafting')
export const Expand = docketIcon('panel-open')
export const Files = docketIcon('projects')
export const Filter = docketIcon('filter')
export const Finished = docketIcon('tasks')
export const Fold = docketIcon('panel-close')
export const Folder = docketIcon('dossier')
export const FolderAdd = docketIcon('folder-add')
export const FolderChecked = docketIcon('archive')
export const FolderOpened = docketIcon('dossier')
export const FullScreen = docketIcon('fullscreen')
export const Grid = docketIcon('dashboard')
export const Hide = docketIcon('hide')
export const Histogram = docketIcon('chart')
export const InfoFilled = docketIcon('info')
export const Key = docketIcon('key')
export const Link = docketIcon('link')
export const List = docketIcon('list')
export const Loading = docketIcon('loading')
export const Location = docketIcon('location')
export const Lock = docketIcon('lock')
export const MagicStick = docketIcon('ai')
export const Medal = docketIcon('seal')
export const Memo = docketIcon('file')
export const Menu = docketIcon('dashboard')
export const Message = docketIcon('mail')
export const Microphone = docketIcon('microphone')
export const Minus = docketIcon('minus')
export const Monitor = docketIcon('ocr')
export const More = docketIcon('more')
export const Notebook = docketIcon('knowledge')
export const Notification = docketIcon('reminder')
export const OfficeBuilding = docketIcon('building')
export const Open = docketIcon('panel-open')
export const Opportunity = docketIcon('lightbulb')
export const Paperclip = docketIcon('attachment')
export const Phone = docketIcon('phone')
export const Picture = docketIcon('picture')
export const PieChart = docketIcon('chart')
export const Plus = docketIcon('plus')
export const Position = docketIcon('open')
export const Postcard = docketIcon('file')
export const Printer = docketIcon('printer')
export const Promotion = docketIcon('open')
export const QuestionFilled = docketIcon('help')
export const Rank = docketIcon('sort')
export const Reading = docketIcon('knowledge')
export const Refresh = docketIcon('sync')
export const RefreshLeft = docketIcon('refresh-left')
export const RefreshRight = docketIcon('refresh-right')
export const Right = docketIcon('arrow-right')
export const ScaleToOriginal = docketIcon('fullscreen')
export const Search = docketIcon('search')
export const Select = docketIcon('check')
export const SetUp = docketIcon('settings')
export const Setting = docketIcon('settings')
export const Share = docketIcon('relation')
export const Star = docketIcon('star')
export const Suitcase = docketIcon('cases')
export const Sunny = docketIcon('today')
export const Switch = docketIcon('sync')
export const SwitchButton = docketIcon('power')
export const Tickets = docketIcon('file')
export const Timer = docketIcon('waiting')
export const Tools = docketIcon('settings')
export const Top = docketIcon('arrow-up')
export const TopRight = docketIcon('open')
export const TrendCharts = docketIcon('chart')
export const Upload = docketIcon('upload')
export const UploadFilled = docketIcon('upload')
export const User = docketIcon('user')
export const UserFilled = docketIcon('user')
export const VideoPlay = docketIcon('play')
export const View = docketIcon('view')
export const Warning = docketIcon('risk')
export const ZoomIn = docketIcon('zoom-in')
export const ZoomOut = docketIcon('zoom-out')
export const BrandSeal = docketIcon('brand-seal')
export const Waiting = docketIcon('waiting')
